CREATE WAREHOUSE IF NOT EXISTS MARKET_ETL_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS MARKET_ETL_DB;
CREATE SCHEMA IF NOT EXISTS MARKET_ETL_DB.RAW;
CREATE SCHEMA IF NOT EXISTS MARKET_ETL_DB.MARTS;

CREATE TABLE IF NOT EXISTS MARKET_ETL_DB.RAW.ECON_SERIES (
    series_id   VARCHAR(20),
    metric      VARCHAR(50),
    obs_date    DATE,
    value       FLOAT,
    loaded_at   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);